# NDArrays

*   Numpy defines an n-dimensional array where every element in the array has the same data type
*  Examples: float32, float64, int32, int64, etc.
* It is common to use high-dimensional arrays in Numpy
* There are many typical ways to allocate new arrays in Numpy



## Defining Arrays

In [1]:
import numpy as np

In [3]:
# 1d array
x1 = np.array([1,2,3,4,5])
x1

array([1, 2, 3, 4, 5])

In [6]:
# 2d array (array of 1d arrays)
x2 = np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 3d array  (Array of 2d arrays)
x3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

There are short-hand ways of defining many common arrays

In [14]:
# 1d array of zeros
x4 = np.zeros(3)
x4

array([0., 0., 0.])

In [15]:
# 2d array of zeros
x5 = np.zeros((3,3))
x5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 3d Array of zeros
x6 = np.zeros((3,3,3))
x6

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# An array of ones
x7 = np.ones(3)
x7

array([1., 1., 1.])

In [20]:
# Numpy will use a default type (often float64)
x7.dtype

dtype('float64')

In [23]:
# However you can define a specific type as follows
x8 = np.ones(3, dtype=np.int64)
x8.dtype

dtype('int64')

In [24]:
# Or you can cast to a differnt type
x9 = x8.astype(np.float32)
x9

array([1., 1., 1.], dtype=float32)

In [28]:
# Another common way to define an array is using arange, which just counts up from 0 by integers
x10 = np.arange(10)
x10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# It has int64 type by default
x10.dtype

dtype('int64')

In [29]:
# You can also define, the start, stop, and step explicitely. These don't have to be integers.
x11 = np.arange(1,10,0.5)
x11

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [31]:
# Another useful function is linspace, which bproduces evenly spaced numbers in an interval
x12 = np.linspace(0.,1.,10)
x12

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Reshaping and Manipulating Arrays