# NDArrays

*   Numpy defines an n-dimensional array where every element in the array has the same data type
*  Examples: float32, float64, int32, int64, etc.
* It is common to use high-dimensional arrays in Numpy
* There are many typical ways to allocate new arrays in Numpy



## Defining Arrays

In [1]:
import numpy as np

In [3]:
# 1d array
x1 = np.array([1,2,3,4,5])
x1

array([1, 2, 3, 4, 5])

In [6]:
# 2d array (array of 1d arrays)
x2 = np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 3d array  (Array of 2d arrays)
x3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
# You can get the shape of an array with .shape
(x1.shape, x2.shape, x3.shape)

((5,), (2, 3), (2, 2, 3))

There are several short-hand ways of defining common arrays

In [14]:
# 1d array of zeros
x4 = np.zeros(3)
x4

array([0., 0., 0.])

In [15]:
# 2d array of zeros
x5 = np.zeros((3,3))
x5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 3d Array of zeros
x6 = np.zeros((3,3,3))
x6

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
# An array of ones
x7 = np.ones(3)
x7

array([1., 1., 1.])

In [20]:
# Numpy will use a default type (often float64)
x7.dtype

dtype('float64')

In [23]:
# However you can define a specific type as follows
x8 = np.ones(3, dtype=np.int64)
x8.dtype

dtype('int64')

In [24]:
# Or you can cast to a differnt type
x9 = x8.astype(np.float32)
x9

array([1., 1., 1.], dtype=float32)

In [28]:
# Another common way to define an array is using arange, which just counts up from 0 by integers
x10 = np.arange(10)
x10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# It has int64 type by default
x10.dtype

dtype('int64')

In [29]:
# You can also define, the start, stop, and step explicitely. These don't have to be integers.
x11 = np.arange(1,10,0.5)
x11

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [31]:
# Another useful function is linspace, which produces evenly spaced numbers in an interval
x12 = np.linspace(0.,1.,10)
x12

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Basic Indexing

In [52]:
# Indexing works how you would expect
x = np.arange(10)
print(x[0], x[1])

0 1


In [53]:
# To get the last element of an array
print(x[-1])

9


In [54]:
# Or second to last ...
print(x[-2])

8


In [55]:
# Things are similar for 2d arrays. The indexes point to rows, then columns.
x = np.array([[1,2,3],[4,5,6]])
print(x[0,0], x[0,1], x[1,0])

1 2 4


In [56]:
# Similarly for 3d arrays.
x = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(x[0,0,0], x[0,0,1], x[1,0,0])

1 2 7


In [57]:
# You can think of this notation as dissecting the array into subarrays. For example,
# let's look at x[1]. It's a 2d array
x[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [46]:
# The notation x[1][1] or x[1,1] pulls out the second row of x[1]
print(x[1][1], x[1,1])

[10 11 12] [10 11 12]


In [58]:
# The notation x[1][1][2] or x[1,1,2] pulls out the third element of the second row of x[1]
print(x[1][1][2], x[1,1,2])

12 12


## More Advanced Indexing

In [60]:
# Slicing let's pull out portions of an array
y1 = np.arange(20)
y1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
y1[5:9]

array([5, 6, 7, 8])

**From the Numpy guide:**
*The basic slice syntax is $i:j:k$ where $i$ is the starting index, $j$ is the stopping index, and $k$ is the step ($k \neq 0$)
). This selects the m elements (in the corresponding dimension) with index values $i, i + k, …, i + (m - 1) k$ where
 and $q$ and $r$ are the quotient and remainder obtained by dividing $j - i$ by $k: j - i = q k + r$, so that $i + (m - 1) k < j$.*


In [64]:
# Basically, you can take steps bigger than 1 when slicing
y1[5:9:2]

array([5, 7])

In [65]:
# There is special syntax for slicing from the beginning of an array
y1[:5]

array([0, 1, 2, 3, 4])

In [66]:
# Or for slicing to the end of an array
y1[5:]

array([5, 6, 7, 8, 9])